clear;
clc; 
close all;
fid=fopen('MATRIX_DATA/matrix_mul_col_NOMP.txt');
data=textscan(fid,'%d %f');
fclose ( fid );
x=data{1};
quicksort_y=data{2};
fid=fopen('MATRIX_DATA/matrix_mul_col_OMP.txt');
data=textscan(fid,'%d %f')
fclose ( fid );
mergesort_y=data{2};
fid=fopen('MATRIX_DATA/matrix_mul_row_NOMP.txt');
data=textscan(fid,'%d %f');
fclose ( fid );
heapsort_y=data{2};
fid=fopen('MATRIX_DATA/matrix_mul_row_OMP.txt');
data=textscan(fid,'%d %f');
fclose ( fid );
shellsort_y =data{2};
figure ;
title ('m*m algorithms');
xlabel('n [-]');
ylabel('t [s]');
hold on;
plot(x, quicksort_y);
plot(x, mergesort_y);
plot(x,heapsort_y);
plot(x, shellsort_y );
legend('COL NO OMP','COL OMP','ROW NO OMP','ROW OMP','Location','northwest');
hold off ;
